client_id = "5c0a85f4b21187c3b4fd41a34c688a6a"
name = "RabbitLoader"
handle = "rabbitloader"
application_url = "https://shopify.rb8.in/"
embedded = true

scopes = "read_products,write_products,read_script_tags,write_script_tags,read_content,write_content,read_themes,write_themes"

[build]
automatically_update_urls_on_dev = true

[access_scopes]
use_legacy_install_flow = false

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/installed"]
uri = "/webhooks/app/installed"

[[webhooks.subscriptions]]
topics = ["products/create"]
uri = "/webhooks/products/create"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products/update"

[auth]
redirect_urls = [
  "https://shopify.rb8.in/shopify/auth/callback"
]

[pos]
embedded = false